---
- name: Install Docker and Login to registry
  hosts:
    - puzzle15_builder
    - puzzle15_stage
  become: true
  gather_facts: false

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - gnupg
          - python3-pip
        update_cache: true
        state: present

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        owner: root
        group: root
        mode: '0755'
        state: directory

    - name: Gather distribution_release facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - distribution
          - distribution_release

    - name: Add Docker's official GPG key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{
          ansible_distribution | lower }}/gpg"
        dest: /etc/apt/keyrings/docker.asc
        owner: root
        group: root
        mode: '0644'
        checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570

    - name: Setup Docker's official repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/{{ ansible_distribution | lower }}
          {{ ansible_distribution_release }} stable
        state: present
        filename: docker

    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
        state: present

    - name: Install docker python package
      ansible.builtin.pip:
        name: docker

    - name: Log into Docker registry
      community.docker.docker_login:
        registry_url: cr.yandex
        username: json_key
        password: "{{
            lookup(
              'ansible.builtin.file',
              lookup('ansible.builtin.env', 'yc_key_file')
            ) | string
          }}"
